spring:
  application:
    name: employee-service
  config:
    import: "optional:configserver:http://localhost:8088"

#server:
#  port: 8085

grpc:
  client:
    salarym-service:
      address: discovery://salarym-service
    negotiationType: PLAINTEXT

#logging:
#  level:
#    org.springframework: DEBUG
#    com.dailycodebuffer: DEBUG





